use uday_project;
select * from products;
select * from orders;
select * from order_items;
select * from customers;
 -- queries
-- 1.	Display all customers from Pune.
select customer_name,city from customers
where city ="Pune";
-- 2.	List all products in the Electronics category.
select product_name,category from products
where category ="Electronics";
-- 3.	Find all orders with status = 'Completed'.
select * from orders
where status='Completed';
-- 4.	Show top 10 most expensive products.
select * from products
order by price desc limit 10;
-- 5.	Find customers whose email is missing.
select customer_name,email from customers
where email = null;
-- 6.	Find total sales amount (sum of total_amount).
select sum(total_amount) from order_items;
-- 7.	Find average product price by category.
select avg(price) ,category from products
group by category;
-- 8.Count number of orders for each status.
select  count(status) as count_of_status ,status from orders
group by status;
-- 9.	Find total quantity sold for each product.
select sum(quantity) as total_qty,product_id from order_items  
group by product_id;
-- 10.	Find maximum and minimum order amount.
SELECT 
    MAX(total_amount) AS max_order_amount,MIN(total_amount) AS min_order_amount
FROM order_items;
-- 11.	Display order_id, customer_name, order_date, and status.
select order_id,customer_name,order_date,status from orders o 
join customers c on c.customer_id =o.customer_id ;
-- 12.	Show customer_name, product_name, quantity, and total_amount for each sale.
SELECT 
    c.customer_name,p.product_name,oi.quantity,oi.total_amount,o.order_date FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON oi.product_id = p.product_id
ORDER BY o.order_date;
-- 13.	Find total sales done by each customer.
SELECT c.customer_id,c.customer_name,SUM(oi.total_amount) AS total_sales FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_items oi ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY c.customer_id, c.customer_name
ORDER BY total_sales DESC;
-- 14.	Find total revenue generated by each category.
SELECT p.category,SUM(oi.total_amount) AS total_revenue FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.status = 'Completed'
GROUP BY p.category ORDER BY total_revenue DESC;
-- 15.  Find customers who have placed more than 3 orders.
SELECT c.customer_id,c.customer_name,COUNT(o.order_id) AS order_count FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name HAVING COUNT(o.order_id) > 3;
-- 16.	Find products whose total sales amount is greater than 1,00,000.
SELECT p.product_id,p.product_name,SUM(oi.total_amount) AS total_sales FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.status = 'Completed' 
GROUP BY p.product_id, p.product_name HAVING SUM(oi.total_amount) > 100000;
-- 17.	Show city-wise total sales.
SELECT c.city,SUM(oi.total_amount) AS total_sales
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY c.city
ORDER BY total_sales DESC;
-- 18.	Replace missing discount values with 0 and calculate final amount.
SELECT oi.order_item_id,oi.order_id,oi.product_id,oi.quantity,
    COALESCE(oi.discount, 0) AS discount,(oi.total_amount - (oi.total_amount * COALESCE(oi.discount, 0))) AS final_amount
FROM order_items oi;
-- 19.	Show order status as: Done’ for Completed , ‘Waiting’ for Pending , ‘Rejected’ for Cancelled. 
SELECT order_id,customer_id, order_date,
    CASE 
        WHEN status = 'Completed' THEN 'Done'
        WHEN status = 'Pending' THEN 'Waiting'
        WHEN status = 'Cancelled' THEN 'Rejected'
    END AS order_status
FROM orders;
-- 20.	Find customers who have never placed any order.
SELECT c.customer_id,c.customer_name FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_id is NULL;